#!/bin/sh

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

cd $HOME

# Make passwordless sudo work
export SUDO_ASKPASS=/bin/true


# A bit of a hack
# mv .gitconfig .gitconfig.private

git clone https://github.com/sjotterman/dotfiles dotfiles

mv .bashrc .bashrc.old
mv .zshrc .zshrc.old

# install tea
sh <(curl tea.xyz) --yes
# Install stow
STOW_VERSION=2.3.1
curl -L http://mirror.us-midwest-1.nexcess.net/gnu/stow/stow-${STOW_VERSION}.tar.gz | tar xzC $HOME/
cd $HOME/stow-${STOW_VERSION}
./configure --prefix=$HOME/.local && make install

# Install fzf
FZF_VERSION=0.38.0
curl -L https://github.com/junegunn/fzf/releases/download/${FZF_VERSION}/fzf-${FZF_VERSION}-linux_amd64.tar.gz | tar xzC $HOME/.local/bin

curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
sudo dpkg -i ripgrep_13.0.0_amd64.deb


cd $HOME/stow
stow */

# Install neovim with tea
nvim~0.8.3 -v

# Install fzf with tea
fzf~0.38.0 --version
