#!/usr/bin/env bash

if [ -z "$USER" ]; then
    USER=$(id -un)
fi

echo >&2 "====================================================================="
echo >&2 " Setting up codespaces environment"
echo >&2 ""
echo >&2 " USER        $USER"
echo >&2 " HOME        $HOME"
echo >&2 "====================================================================="

cd $HOME

# Make passwordless sudo work
export SUDO_ASKPASS=/bin/true


# A bit of a hack
# mv .gitconfig .gitconfig.private

git clone https://github.com/sjotterman/dotfiles dotfiles

git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"

mv .bashrc .bashrc.old
mv .zshrc .zshrc.old

# Install stow
STOW_VERSION=2.3.1
curl -L http://mirror.us-midwest-1.nexcess.net/gnu/stow/stow-${STOW_VERSION}.tar.gz | tar xzC $HOME/
cd $HOME/stow-${STOW_VERSION}
./configure --prefix=$HOME/.local && make install

# Install neovim
cd $HOME
curl -L  https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb --output nvim.deb
sudo apt install ./nvim.deb

cd $HOME/dotfiles
stow */

# Install fzf
FZF_VERSION=0.38.0
curl -L https://github.com/junegunn/fzf/releases/download/${FZF_VERSION}/fzf-${FZF_VERSION}-linux_amd64.tar.gz | tar xzC $HOME/.local/bin

curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
sudo dpkg -i ripgrep_13.0.0_amd64.deb
